name: 02-code-quality

on:
  workflow_call:

jobs:
  code-quality:
    runs-on: self-hosted
    services:
      mysql:
        image: mysql:8.0.21
        env:
          MYSQL_DATABASE: ecommerce
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping"
    steps:
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
  
      - name: Add PHP repository
        run: |
          sudo add-apt-repository ppa:ondrej/php
          sudo apt-get update
  
      - name: Install PHP 7.4
        run: |
          sudo apt-get install -y php7.4 php7.4-cli php7.4-fpm php7.4-json php7.4-common php7.4-mysql php7.4-zip php7.4-gd php7.4-mbstring php7.4-curl php7.4-xml php7.4-bcmath php7.4-json
  

    #   - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
    #     with:
    #       php-version: '7.4'
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: |
          php artisan key:generate
      - name: Directory Permissions
        run: |
          chmod -R 777 storage bootstrap/cache
      - name: phpstan
        run: |
          composer require --dev phpstan/phpstan
          ./vendor/bin/phpstan analyse --memory-limit=1G --level max app || true
      - name: phpinsights
        run: |
          composer config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
          composer require nunomaduro/phpinsights:^1.0 --dev --with-all-dependencies
          php artisan vendor:publish --provider="NunoMaduro\PhpInsights\Application\Adapters\Laravel\InsightsServiceProvider"
          php artisan insights --no-interaction --min-quality=90 --min-complexity=90 --min-architecture=90 --min-style=90 --ansi --format=github-action || true