name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Change this to your default branch
  workflow_dispatch:

jobs:
  build:
      runs-on: ubuntu-latest 
      container:
          image: mahmoudabdelaziz22/ssh-operator-base
          options: --privileged  # Optional: Add privileged mode if needed
          
      steps:
        - name: Print "Hello"
          run: echo "Hello from inside Container"
